# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d942d0b05bf87e54f7e9651d311e248a69c8d33f42373962b9d3e88348aeddb1f494f18adf81a24e1bbce5e451e97af5c4e3a3443559e6bc13cbee8b73abd4c

test:
  secret_key_base: 0a3d6edcbccf0738dc1acaad879ec8ab35186302d1cb62b6f808f5a828471a123ecf3281ed7fccb47d5f2a5aeeff3bf5eeb93c7d457f183b7df72efdc5bb2226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
